<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PageContent extends Model
{
    protected $fillable = [
        'hero_eyebrow',
        'hero_title_line_1',
        'hero_title_line_2',
        'hero_lead',
        'hero_cta_text',
        'hero_cta_link',
        'hero_banner_path',
        'about_eyebrow',
        'about_heading',
        'about_lead',
        'who_eyebrow',
        'who_heading',
        'who_lead',
        'audiences',
        'belief_eyebrow',
        'belief_lead',
        'why_now_eyebrow',
        'why_now_heading',
        'why_now_insights',
        'why_now_source',
        'transform_eyebrow',
        'transforms',
        'process_eyebrow',
        'process_heading',
        'process_steps',
        'why_eyebrow',
        'why_tagline',
        'why_paragraph_1',
        'why_paragraph_2',
        'why_paragraph_3',
        'regions_eyebrow',
        'regions_lead',
        'regions',
        'founder_eyebrow',
        'founder_name',
        'founder_role',
        'founder_hook',
        'founder_paragraph_1',
        'founder_paragraph_2',
        'founder_paragraph_3',
        'founder_credentials',
        'founder_quote',
        'founder_quote_footer',
        'cta_eyebrow',
        'cta_heading',
        'cta_body',
        'cta_button_text',
        'cta_button_link',
        'mission_banner_path',
        'mission_eyebrow',
        'mission_heading',
        'mission_paragraph_1',
        'mission_paragraph_2',
        'mission_closing',
        'mission_cta_eyebrow',
        'mission_cta_heading',
        'mission_cta_body',
        'mission_cta_button_text',
        'mission_cta_button_link',
    ];

    protected $casts = [
        'audiences' => 'array',
        'why_now_insights' => 'array',
        'transforms' => 'array',
        'process_steps' => 'array',
        'regions' => 'array',
        'founder_credentials' => 'array',
    ];

    public static function defaults(): array
    {
        return [
            'hero_eyebrow' => 'SAKOUR Family Enterprise — Legacy, Leadership, Future Readiness',
            'hero_title_line_1' => 'Legacy is',
            'hero_title_line_2' => 'a Verb.',
            'hero_lead' => 'Three decades. Three continents. One mission: guiding family enterprises whose wealth means more than money — through leadership, succession, and the future they\'re building.',
            'hero_cta_text' => 'Start a Legacy Conversation',
            'hero_cta_link' => '/booking',
            'hero_banner_path' => null,
            'about_eyebrow' => null,
            'about_heading' => 'Family business is one of the most powerful forms of enterprise in the world — and one of the most personal.',
            'about_lead' => "Behind every decision, there is a story.\nBehind every transition, there is a family.\nBehind every legacy, there is a next generation preparing to carry it forward.",
            'who_eyebrow' => 'Who We Serve',
            'who_heading' => 'Founders, family business owners, and next-generation leaders.',
            'who_lead' => 'At SAKOUR Family Enterprise, we work alongside founders, family business owners, and next-generation leaders as they navigate growth, governance, succession, leadership, and transformation — with clarity, not just complexity.',
            'audiences' => [
                [
                    'title' => 'Founders',
                    'body' => 'You built something from nothing. Now you\'re thinking about what happens to it — and who it becomes — without you at the center of every decision.',
                ],
                [
                    'title' => 'Family Business Owners',
                    'body' => 'You\'re balancing the business, the family, and everything in between. You need clarity on governance, roles, and what "fair" actually means for the next chapter.',
                ],
                [
                    'title' => 'Next-Generation Leaders',
                    'body' => 'You\'re stepping into a legacy you didn\'t build, but are expected to carry. You want to lead in your own way — without losing what made the business work.',
                ],
            ],
            'belief_eyebrow' => 'Our Belief',
            'belief_lead' => 'For us, family enterprise isn\'t only about wealth, ownership, or continuity. It\'s about legacy, responsibility, identity, and relationships — and the courage to prepare the next generation to lead well in the era of AI, while staying deeply connected to the values that hold the family together.',
            'why_now_eyebrow' => 'Why It Matters Now',
            'why_now_heading' => 'Enduring family enterprises prepare deliberately.',
            'why_now_insights' => [
                ['text' => 'Fewer than half of family business leaders have a formal succession plan in place — yet those who do describe it as the single most important decision they ever made.'],
                ['text' => 'The next generation engages when the business has visible purpose and social impact — purpose, not pressure, is what carries a legacy across generations.'],
                ['text' => 'Legacy is the connective tissue between a family\'s values, its business purpose, and what it hopes to pass forward — a gift and a responsibility.'],
            ],
            'why_now_source' => 'Source: KPMG International & STEP Project Global Consortium — "Empowering the Future of Family Business" (Global Family Business Survey, 1,800+ businesses, 33 countries)',
            'transform_eyebrow' => 'What We Help Families Do',
            'transforms' => [
                ['from' => 'Complexity', 'to' => 'Clarity'],
                ['from' => 'Transition', 'to' => 'Alignment'],
                ['from' => 'Inherited Responsibility', 'to' => 'Intentional Leadership'],
            ],
            'process_eyebrow' => 'How We Work',
            'process_heading' => 'A process built for how families actually change.',
            'process_steps' => [
                [
                    'label' => 'Listen',
                    'title' => 'Understand the story',
                    'body' => 'Not just the business\'s numbers, but the relationships, history, and unspoken expectations behind them.',
                ],
                [
                    'label' => 'Clarify',
                    'title' => 'Name what\'s real',
                    'body' => 'Where alignment exists, where it doesn\'t, and what needs deciding before it becomes a crisis.',
                ],
                [
                    'label' => 'Guide',
                    'title' => 'Work alongside you',
                    'body' => 'Governance design, succession planning, and leadership development — at a pace your family can sustain.',
                ],
                [
                    'label' => 'Sustain',
                    'title' => 'Stay engaged',
                    'body' => 'Legacy isn\'t a one-time decision. We stay with you as your family and business evolve.',
                ],
            ],
            'why_eyebrow' => 'Why SAKOUR',
            'why_tagline' => 'Businesses don\'t grow until their leaders do.',
            'why_paragraph_1' => 'Family enterprises rarely fail for lack of strategy. They fail when leadership, family alignment, and culture can\'t carry the strategy they already have. So our work begins where every plan will ultimately succeed or fail: with the leader — then moves outward to the family, the culture, and the enterprise.',
            'why_paragraph_2' => 'Most advisors bring one lens — legal, financial, or governance. SAKOUR was built differently: from decades inside the room where enterprise transformation actually happens, a rigorous formal grounding in family business governance and succession, a hands-on coaching practice — and the lived experience of a family business owner.',
            'why_paragraph_3' => 'We don\'t bring a single playbook. What works for a third-generation Gulf conglomerate rarely works the same way for a European family institution or an African family enterprise entering its next chapter. Real guidance has to be earned across cultures, not templated.',
            'regions_eyebrow' => 'Where We Work',
            'regions_lead' => 'One practice, four worlds — and the cross-border families who span them. Because guidance has to be earned in a culture, not imported into it.',
            'regions' => [
                [
                    'title' => 'United Kingdom',
                    'body' => 'Where SAKOUR is rooted — home of our UK retreats, the Edinburgh & Glasgow Leadership Games, and our Cambridge-grounded practice.',
                ],
                [
                    'title' => 'Europe',
                    'body' => 'Multi-generational family institutions navigating succession, professionalization, and a next generation that demands purpose.',
                ],
                [
                    'title' => 'Middle East',
                    'body' => 'Three decades of C-level trust across the region — where family, faith, and enterprise have never been separate things.',
                ],
                [
                    'title' => 'Indonesia & Southeast Asia',
                    'body' => 'Home of our royal retreat, and a rising generation of family enterprises bridging tradition and transformation.',
                ],
            ],
            'founder_eyebrow' => 'Our Founder',
            'founder_name' => 'Raouda Sakour',
            'founder_role' => null,
            'founder_hook' => 'Raouda doesn\'t just advise family businesses. She owns and leads one.',
            'founder_paragraph_1' => 'As an owner of a family property business, the questions her clients carry are questions she lives with too — how to grow what the family has built, how to be fair to both the business and the relationships behind it, and how to prepare what comes next without losing what matters most.',
            'founder_paragraph_2' => 'She pairs that insider\'s understanding with an outsider\'s rigor: 26+ years inside some of the world\'s leading technology organizations — Oracle, Accenture, Capgemini, and Cognizant — leading digital and cloud transformation with C-level leaders across the Middle East, Europe, the UK, and Africa.',
            'founder_paragraph_3' => 'She completed the Cambridge Judge Business School Family Business Leadership Programme, and is a Certified John Maxwell Coach and DISC Consultant since 2020 — currently in Maxwell Leadership\'s Executive Director Program — as well as a Certified John Maxwell Youth Coach, a credential she carries into every next-generation engagement, because preparing young leaders is not a service line for her. It\'s her heart.',
            'founder_credentials' => [
                'Family Business Owner',
                'Oracle · Accenture · Capgemini · Cognizant',
                'Cambridge Judge — Family Business Leadership',
                'Maxwell Coach · DISC Consultant · Youth Coach',
            ],
            'founder_quote' => 'A pilot is trained to see the whole landscape at once, to stay calm when visibility drops, and to always have a flight plan. I bring the same discipline to family enterprises — I call it leadership with altitude.',
            'founder_quote_footer' => 'Raouda Sakour — Pilot in training, Edinburgh',
            'cta_eyebrow' => 'Get In Touch',
            'cta_heading' => 'Start a conversation about your next chapter.',
            'cta_body' => 'Have questions, comments, or inquiries? We would love to hear from you and help map your growth path.',
            'cta_button_text' => 'Book a Discovery Call',
            'cta_button_link' => '/contact',
            'mission_banner_path' => null,
            'mission_eyebrow' => 'The SAKOUR Mission',
            'mission_heading' => 'One million futures.',
            'mission_paragraph_1' => 'SAKOUR Family Enterprise exists for a purpose larger than itself. Raouda\'s lifetime mission is to fund the education of one million medical students around the world — young people with the calling to heal, and without the means to get there.',
            'mission_paragraph_2' => 'It began in 2017, with her charitable foundation sponsoring medical students in Syria and supporting communities across Africa. A quarter of everything SAKOUR earns serves this mission — which means every family we work with becomes part of it. Every leader who grows, every succession that succeeds, every business that thrives sends another young person toward medicine.',
            'mission_closing' => 'When your family business grows, another family\'s future grows with it.',
            'mission_cta_eyebrow' => 'Be Part of It',
            'mission_cta_heading' => 'Every engagement moves the mission forward.',
            'mission_cta_body' => 'Start a conversation about your family enterprise — and become part of one million futures.',
            'mission_cta_button_text' => 'Start a Legacy Conversation',
            'mission_cta_button_link' => '/booking',
        ];
    }
}
